import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { validate } from '../js/schema.js';
import { securityKeys } from './validate-data.mjs';
import { comparable, assetPath, escape } from '../js/utils.js';
import { chart } from '../js/charts.js';
import { coachingView } from '../js/coaching.js';
const bundle=JSON.parse(await readFile(new URL('../data/demo.json',import.meta.url),'utf8'));
const clone=x=>JSON.parse(JSON.stringify(x));
assert.deepEqual(validate('demo',bundle,true),[]);
const mixed=clone(bundle.history);
const mixedRecord=mixed.records[0];
mixedRecord.workingWeights=[mixedRecord.weight,mixedRecord.weight-5,mixedRecord.weight-10];
mixedRecord.volume=mixedRecord.reps.reduce((sum,reps,i)=>sum+reps*mixedRecord.workingWeights[i],0);
assert.deepEqual(validate('history',mixed,true),[]);
mixedRecord.volume+=1;assert(validate('history',mixed,true).length);
mixedRecord.volume-=1;mixedRecord.workingWeights.pop();assert(validate('history',mixed,true).length);
const mixedPlan=clone(bundle.latest);mixedPlan.exercises[0].workingWeights=[70,65,60];
assert.deepEqual(validate('latest',mixedPlan,true),[]);
mixedPlan.exercises[0].workingWeights[0]=65;assert(validate('latest',mixedPlan,true).length);
const timedHistory=clone(bundle.history);
timedHistory.sessions[0].timedExercises=[{id:'front-plank',name:'Front Plank',durationSeconds:[94,94]}];
assert.deepEqual(validate('history',timedHistory,true),[]);
timedHistory.sessions[0].timedExercises[0].durationSeconds=[-1];assert(validate('history',timedHistory,true).length);
const invalid=clone(bundle.latest);invalid.exercises[0].previous.comparisonGroup='different-machine';assert(validate('latest',invalid).length);
const badReps=clone(bundle.latest);badReps.exercises[0].targetReps=[10];assert(validate('latest',badReps).length);
const badDate=clone(bundle.latest);badDate.generatedAt='2026-02-30T05:00:00Z';assert(validate('latest',badDate).length);
assert(validate('latest',{...bundle.latest,schemaVersion:2}).length);
assert(validate('latest',null).length);
assert.deepEqual(validate('history',{schemaVersion:1,sessions:[],records:[]}),[]);
const badHistory=clone(bundle.history);badHistory.records[0].sessionId='missing';assert(validate('history',badHistory).length);
assert(securityKeys({safe:{access_token:'example'}}).length);
assert.deepEqual(securityKeys({name:'Token display text is harmless'}),[]);
assert(validate('latest',{...bundle.latest,accountId:'example'},true).length);
const ex=bundle.latest.exercises[0];const rows=comparable(bundle.history.records,ex);
assert(rows.every(r=>r.comparisonGroup===ex.comparisonGroup&&r.unit===ex.unit));
assert.equal(comparable([{...rows[0],unit:'lb'},{...rows[0],comparisonGroup:'other'}],ex).length,0);
assert.equal(assetPath({...ex,image:'https://example.invalid/x.svg'}),'assets/exercises/fallback.svg');
assert.equal(escape('<script>'),'&lt;script&gt;');
assert(chart([], 'weight').includes('legalább két'));
assert(chart(rows).includes('Grafikonértékek'));
const gap=chart([{date:'2026-01-01',weight:10},{date:'2026-01-02',weight:null},{date:'2026-01-03',weight:12}]);
assert.match(gap,/d="M[^"]* M/);
const upstream={...bundle.latest,status:'upstream_error'};assert.deepEqual(validate('latest',upstream),[]);
const coached=clone(bundle.latest);
coached.coaching={generatedAt:'2026-09-30T12:00:00Z',assessment:'insufficient_data',evaluation:'<script>alert(1)</script>',evidence:[],advice:[],possibleCauses:[{text:'Rest may differ',confidence:'hypothesis'}],alternative:null,followUp:[]};
assert.deepEqual(validate('latest',coached,true),[]);
assert(coachingView(coached.coaching).includes('&lt;script&gt;'));
assert(coachingView(coached.coaching).includes('Feltételezés'));
assert(coachingView(null).includes('Még nincs'));
coached.coaching.possibleCauses[0].confidence='certain';assert(validate('latest',coached,true).length);
coached.coaching.possibleCauses[0].confidence='hypothesis';
coached.coaching.alternative={name:'Other exercise',reason:'Conditional',condition:'Only if reviewed'};
coached.exercises[0].coaching=clone(coached.coaching);assert.deepEqual(validate('latest',coached,true),[]);
delete coached.coaching.alternative.condition;assert(validate('latest',coached,true).length);
const unclassified=clone(bundle.history);unclassified.sessions[0].workoutType=null;
for(const record of unclassified.records.filter(r=>r.sessionId===unclassified.sessions[0].id))record.workoutType=null;
assert.deepEqual(validate('history',unclassified,true),[]);
console.log('GainMap: schema, privacy, comparability, coaching, chart gaps, and fallback checks passed.');
