import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { validate } from '../js/schema.js';
import { securityKeys } from './validate-data.mjs';
import { comparable, assetPath, escape } from '../js/utils.js';
import { chart } from '../js/charts.js';
const bundle=JSON.parse(await readFile(new URL('../data/demo.json',import.meta.url),'utf8'));
const clone=x=>JSON.parse(JSON.stringify(x));
assert.deepEqual(validate('demo',bundle,true),[]);
const invalid=clone(bundle.latest);invalid.exercises[0].previous.comparisonGroup='different-machine';assert(validate('latest',invalid).length);
const badReps=clone(bundle.latest);badReps.exercises[0].targetReps=[10];assert(validate('latest',badReps).length);
const badDate=clone(bundle.latest);badDate.generatedAt='2026-02-30T05:00:00Z';assert(validate('latest',badDate).length);
assert(validate('latest',{...bundle.latest,schemaVersion:2}).length);
assert(validate('latest',null).length);
assert.deepEqual(validate('history',{schemaVersion:1,sessions:[],records:[]}),[]);
const badHistory=clone(bundle.history);badHistory.records[0].sessionId='missing';assert(validate('history',badHistory).length);
assert(securityKeys({safe:{access_token:'example'}}).length);
assert.deepEqual(securityKeys({name:'Token display text is harmless'}),[]);
assert(validate('latest',{...bundle.latest,accountId:'example'},true).length);
const ex=bundle.latest.exercises[0];const rows=comparable(bundle.history.records,ex);
assert(rows.every(r=>r.comparisonGroup===ex.comparisonGroup&&r.unit===ex.unit));
assert.equal(comparable([{...rows[0],unit:'lb'},{...rows[0],comparisonGroup:'other'}],ex).length,0);
assert.equal(assetPath({...ex,image:'https://example.invalid/x.svg'}),'assets/exercises/fallback.svg');
assert.equal(escape('<script>'),'&lt;script&gt;');
assert(chart([], 'weight').includes('legalább két'));
assert(chart(rows).includes('Grafikonértékek'));
const gap=chart([{date:'2026-01-01',weight:10},{date:'2026-01-02',weight:null},{date:'2026-01-03',weight:12}]);
assert.match(gap,/d="M[^"]* M/);
const upstream={...bundle.latest,status:'upstream_error'};assert.deepEqual(validate('latest',upstream),[]);
console.log('GainMap: schema, privacy, comparability, chart gaps, and fallback checks passed.');
